import { Container, Header } from '@/components/shared';
import { nunito } from '@/lib/font';
import { cn } from '@/lib/utils';
import { Suspense } from 'react';

export const metadata = {
  title: 'Next pizza | Оформление',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className={cn('min-h-screen bg-[#F4F1EE]', nunito.className)}>
      <Container>
        <Suspense>
          <Header className="border-b-gray-200" hasSearch={false} hasCart={false} />
          {children}
        </Suspense>
      </Container>
    </main>
  );
}
